# Generated by Django 5.0.7 on 2024-08-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='curso',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
